from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfgen import canvas
import os
from io import BytesIO


def create_pdf(candidate_name, resume_text, output_path="CareerCraftAI_Resume.pdf"):
    """
    Generates a professionally styled PDF resume with CareerCraft AI branding.
    """

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=50,
        rightMargin=50,
        topMargin=80,
        bottomMargin=50,
    )

    # ---------- Brand Styles ----------
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="Title",
        fontName="Helvetica-Bold",
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=12,
        textColor="#003366"
    ))
    styles.add(ParagraphStyle(
        name="Section",
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        spaceBefore=10,
        spaceAfter=6,
        textColor="#003366"
    ))
    styles.add(ParagraphStyle(
        name="Body",
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="Footer",
        fontSize=9,
        alignment=TA_CENTER,
        textColor="gray",
        spaceBefore=12
    ))

    # ---------- Header/Footer Callbacks ----------
    def add_header_footer(canvas, doc):
        canvas.saveState()

        # Header bar
        canvas.setFillColor("#003366")
        canvas.rect(0, A4[1] - 60, A4[0], 60, fill=True, stroke=False)

        # Brand name
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 14)
        canvas.drawString(50, A4[1] - 40, "⚡ CareerCraft AI")

        # Logo (optional)
        logo_path = os.path.join("assets", "logo.png")
        if os.path.exists(logo_path):
            canvas.drawImage(logo_path, A4[0] - 100, A4[1] - 55, width=45, height=45, mask='auto')

        # Footer
        canvas.setStrokeColor("#CCCCCC")
        canvas.line(50, 50, A4[0] - 50, 50)
        canvas.setFont("Helvetica", 9)
        canvas.setFillColor("gray")
        canvas.drawCentredString(A4[0] / 2, 38, "Generated by CareerCraft AI — Your AI Resume Tailoring Copilot")

        canvas.restoreState()

    # ---------- Build PDF ----------
    elements = []

    # Candidate Name
    elements.append(Paragraph(f"{candidate_name}", styles["Title"]))
    elements.append(Spacer(1, 8))

    # Clean raw text (remove markdown artifacts)
    clean_text = (
        resume_text.replace("**", "")
        .replace("###", "")
        .replace("##", "")
        .replace("*", "•")
        .replace("|", "")
        .replace("_", "")
        .replace("-", "–")
    )

    # Break into sections based on keywords
    sections = ["SUMMARY", "EDUCATION", "TECHNICAL SKILLS", "PROJECTS", "EXPERIENCE", "CERTIFICATIONS", "LEADERSHIP", "ACHIEVEMENTS"]
    lines = clean_text.split("\n")
    for line in lines:
        line_strip = line.strip()
        if not line_strip:
            continue
        if any(sec in line_strip.upper() for sec in sections):
            elements.append(Spacer(1, 8))
            elements.append(Paragraph(line_strip, styles["Section"]))
        else:
            elements.append(Paragraph(line_strip, styles["Body"]))

    # Build and save
    doc.build(elements, onFirstPage=add_header_footer, onLaterPages=add_header_footer)

    # Save to file
    with open(output_path, "wb") as f:
        f.write(buffer.getvalue())

    buffer.close()
    return output_path
